name: CI

on:
  push:
    branches: [main, dev, feature/**]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/ContactManager.sln

      - name: Check code formatting
        run: dotnet format --verify-no-changes ./src/ContactManager.sln

      - name: Build
        run: dotnet build ./src/ContactManager.sln --configuration Release

      - name: Run tests
        run: dotnet test ./src/ContactManager.Tests --configuration Release
